PRESENTACION/Controllers/BoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ENTIDAD;
using BL;
using System.Drawing;
using System.Web.UI.WebControls;
using System.IO;

namespace PRESENTACION.Controllers
{
    public class BoxController : Controller
    {
        // GET: Box
        BoxBL boxBL = new BoxBL();
        public ActionResult ListadoBox()
        {
            return View(boxBL.ListadoBox());
        }

        [HttpGet]
        public ActionResult ActualizarBox()
        {

            return View();
        }
        [HttpPost]
        public ActionResult ActualizarBox(string txtIdBox, string txtNombreBox, string imagen)
        {
            BoxE boxE = new BoxE();
            boxE.idBox = Convert.ToInt32(txtIdBox);
            boxE.nombreBox = txtNombreBox;

            string path = Server.MapPath("~/Images/" + imagen);
            byte[] byteImagen = StreamFile(path);

            boxE.imagen = byteImagen;

            if (boxBL.ActualizarBox(boxE)) return Content("<script>alert('Actualizado correctamente')</script>");
            else return Content("<script>alert('Error!')</script>");

        }

        private byte[] StreamFile(string filename)
        {
            FileStream fs = new FileStream(filename, FileMode.Open, FileAccess.Read);

            // Create a byte array of file stream length
            byte[] ImageData = new byte[fs.Length];

            //Read block of bytes from stream into the byte array
            fs.Read(ImageData, 0, System.Convert.ToInt32(fs.Length));

            //Close the File Stream
            fs.Close();
            return ImageData; //return the byte data
        }

    }
}

PRESENTACION/Controllers/BoxProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ENTIDAD;
using BL;
using System.Data;

namespace PRESENTACION.Controllers
{
    public class BoxProductosController : Controller
    {
        // GET: BoxProductos

        BoxProductosBL boxProductosBL = new BoxProductosBL();
        BoxBL boxBL = new BoxBL();

        public ActionResult Index()
        {
            List<BoxProductosE> lstBoxProductos = boxProductosBL.ListadoBox();

            List<BoxE> lstBox = boxBL.ListadoBox();

            ViewBag.ListadoBoxProducto = lstBoxProductos;
            ViewBag.ListadoBox = lstBox;

            return View();
        }


    }
}

PRESENTACION/Views/Box/ActualizarBox.cshtml
@{
    ViewBag.Title = "ActualizarBox";
    Layout = "~/Views/Layouts/Menu.cshtml";
}

<h2>ActualizarBox</h2>


<table>
    @using (Html.BeginForm("ActualizarBox", "Box", FormMethod.Post))
    {
        <tr>
            <td>ID</td>
            <td><input type="text" name="txtIdBox" /></td>
        </tr>
        <tr>
            <td>NOMBRE</td>
            <td><input type="text" name="txtNombreBox" /></td>
        </tr>
        <tr>
            <td>Imagen</td>
            <td> <input type="file" id="imagen" name="imagen"/> </td>
        </tr>
        <tr>
            <td><button type="submit">Actualizar</button></td>
        </tr>
    }
</table>

PRESENTACION/Views/Box/ListadoBox.cshtml
@model List<ENTIDAD.BoxE>

@{
    ViewBag.Title = "ListadoBox";
    Layout = "~/Views/Layouts/Menu.cshtml";

}

<h2>Listado Box</h2>

<table border="1">
    <tr>
        <th>ID</th>
        <th>BOX</th>
        <th>IMAGEN</th>
    </tr>
    @foreach (var item in Model)
    {
        var base64 = Convert.ToBase64String(item.imagen);
        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        <tr>
            <td>@item.idBox</td>
            <td>@item.nombreBox</td>
            <td><img src="@imgSrc" width="50" height="50"/></td>
        </tr>
    }
</table>

PRESENTACION/Views/BoxProductos/Index.cshtml
@model ENTIDAD.BoxProductosE

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layouts/Menu.cshtml";

    var lstBoxProductos = ViewBag.ListadoBoxProducto;
    var lstBox = ViewBag.ListadoBox;
}

<br />
<br />
<h2>Inicio</h2>
<br />
<br />
<div style="height:150px;">

    <div class="row">
        <div class="col-lg-1" ></div>
        <div class="col-lg-2" style="background-color:red;">


            @foreach (var lst2 in lstBox)
            {
                var imagen = @lst2.imagen;
                var base64 = Convert.ToBase64String(imagen);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                <img src="@imgSrc" width="200" height="200" />
                foreach (var lst1 in lstBoxProductos)
                {
                    if (lst2.nombreBox == lst1.idBox.nombreBox)
                    {
                        <p>@lst1.idProducto.nombreProducto @lst1.cantidad Kg.</p>
                    }
                }
            }




        </div>
        <div class="col-lg-4" style="background-color:blue;"></div>
        <div class="col-lg-4" style="background-color:green;"></div>

    </div>

</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />

<div >
    <div class="row">
        <div class="col-lg-1"></div>
        <div>
            <table border="1">
                <tr>
                    <th>ID</th>
                    <th>BOX</th>
                    <th>PRODUCTO</th>
                    <th>CANTIDAD</th>
                    <th>PRECIO UNIT</th>
                    <th>PRECIO TOTAL</th>
                    <th>IMAGEN</th>

                </tr>


                @foreach (var item in lstBoxProductos)
                {
                    var base64 = Convert.ToBase64String(item.imagen);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                    <tr>
                        <td>@item.idBoxProducto</td>
                        <td>@item.idBox.nombreBox</td>
                        <td>@item.idProducto.nombreProducto</td>
                        <td>@item.cantidad</td>
                        <td>@item.idProducto.precio</td>
                        <td>@item.total  </td>
                        <td><img src="@imgSrc" width="50" height="50" /></td>
                    </tr>
                }

            </table>
        </div>
    </div>

</div>

PRESENTACION/Views/Layouts/Menu.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Util/js/bootstrap.js"></script>
    <script src="~/Util/js/bootstrap.min.js"></script>
    <link href="~/Util/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Util/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>